### PR TITLE
feat: Add new metadata when create payment position [PAGOPA-1348]

### PR DESCRIPTION
**Pull request by AngeloCaporaso**
#### List of Changes

- Add metadata {`PO_TYPE`, `ACA`} if `IUPD` of posted Payment Position starts with `ACA`.
- Also, the `README.md` file that referenced the old test pipeline has been updated.

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by AngeloCaporaso** [comment]
This PR will be DRAFT until the [other PR](https://github.com/pagopa/pagopa-debt-position/pull/191) introducing metadata management is merged.

**Comment by AngeloCaporaso** [comment]
update_code

**Comment by AngeloCaporaso** [comment]
update_code

**Review by FedericoRuzzier — APPROVED** [review]
LGTM 👍

**Pull request merged**
