### PR TITLE
chore: Remove GET /organizations API [PAGOPA-1133] 

### PR DESCRIPTION
**Pull request by AngeloCaporaso**
#### List of Changes

- The API GET /organizations and all Service and Model classes related were removed

#### Motivation and Context

- This API is already replaced by [gpd-reporting-enrollments](https://github.com/pagopa/pagopa-reporting-orgs-enrollment/blob/bb1359d88e224de19ccdd428f26dd5fe6bc140ec/src/main/java/it/gov/pagopa/reportingorgsenrollment/controller/IEnrollmentsController.java#L78)

#### How Has This Been Tested?

- Smoke test ✅ 

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by AngeloCaporaso** [comment]
update_code

**Comment by AngeloCaporaso** [comment]
update_code

**Comment by AngeloCaporaso** [comment]
update_code

**Review by pasqualespica — APPROVED** [review]
lgtm 👍

**Pull request merged**
